### ISSUE TITLE
hrsc to coco format

### ISSUE THREAD

**Issue by geobao** [lzh420202/FCOSR#17]
hello, 
thanks for your awesome work : )
I am trying to convert the HRSC dataset to coco format so that I can train with it. Is there any tool available in the repo to do that?
I have found this tool:
```
python tools/dataset_converters/pascal_voc.py ${DEVKIT_PATH} [-h] [-o ${OUT_DIR}]
```
However, when I run it, it says:
```
Traceback (most recent call last):
  File "tools/dataset_converters/pascal_voc.py", line 236, in <module>
    main()
  File "tools/dataset_converters/pascal_voc.py", line 210, in main
    raise IOError(f'The devkit path {devkit_path} contains neither '
OSError: The devkit path data/HRSC2016/FullDataSet/ contains neither "VOC2007" nor "VOC2012" subfolder
```
Do you have any tip for that?

**Comment by geobao** [comment]
answering myself. Here it is the script:
`FCOSR/DOTA_devkit/HRSC2COCO.py`

**Comment by geobao** [comment]
And also a preprocessing **_bmp2jpg.py_**

```python
##  在root dir下直接bmp转jpg并删除原图


#############   bmp转jpg ########
# coding:utf-8
import os
from PIL import Image
from tqdm import tqdm

# bmp 转换为jpg
def bmpToJpg(file_path):
   for fileName in tqdm(os.listdir(file_path)):
       newFileName = fileName[0:fileName.find(".bmp")]+".jpg"
       im = Image.open(os.path.join(file_path,fileName))
       rgb = im.convert('RGB')      #灰度转RGB
       rgb.save(os.path.join(file_path,newFileName))

def del_bmp(root_dir=None):
    file_list = os.listdir(root_dir)
    for f in file_list:
        file_path = os.path.join(root_dir, f)
        if os.path.isfile(file_path):
            if f.endswith(".BMP") or f.endswith(".bmp"):
                os.remove(file_path)
                print( " File removed! " + file_path)
        elif os.path.isdir(file_path):
            del_bmp(file_path)

def main():
   file_path = "data/HRSC2016/FullDataSet/AllImages"
   bmpToJpg(file_path)
   #del_bmp(file_path)

if __name__ == '__main__':
   main()
```

**Comment by hardikatnyun** [comment]
Thanks for the code @geobao . 

Also, the COCO format contains rectangular bounding boxes, and the knowledge of oriented bounding box is lost in the conversion.
