### ISSUE TITLE
error of DOTA_devkit/prepare_dota.py

### ISSUE THREAD

**Issue by gys1287009045** [lzh420202/FCOSR#2]
When I use DOTA_devkit, error occured:
Traceback (most recent call last):
  File "DOTA_devkit/prepare_dota.py", line 195, in <module>
    print_arg(args)
  File "DOTA_devkit/prepare_dota.py", line 34, in print_arg
    if scales.scales:
NameError: name 'scales' is not defined

replace 'scales' with 'args'

**Comment by lzh420202** [comment]
Thanks for your reports. We have fixed this bug in the latest code.
