### ISSUE TITLE
nan

### ISSUE THREAD

**Issue by lina926** [lzh420202/FCOSR#5]
训练到第8个epoch后，loss变nan了，请问是哪里出了问题么

**Comment by lzh420202** [comment]
我有时候会出现这个情况，挺玄学的

**Comment by huangquanjin** [comment]
2022-01-25 11:08:18,053 - mmdet - INFO - Epoch [5][1200/1230]   lr: 1.000e-02, eta: 1 day, 1:38:51, time: 0.761, data_time: 0.007, memory: 9025, loss_ProbiouLoss: nan, IOU_mean: nan, loss_QualityFocalLoss: nan, loss: nan, grad_norm: nan
2022-01-25 11:08:25,655 - mmdet - INFO - Epoch [5][1210/1230]   lr: 1.000e-02, eta: 1 day, 1:38:37, time: 0.760, data_time: 0.007, memory: 9025, loss_ProbiouLoss: nan, IOU_mean: nan, loss_QualityFocalLoss: nan, loss: nan, grad_norm: nan
2022-01-25 11:08:33,261 - mmdet - INFO - Epoch [5][1220/1230]   lr: 1.000e-02, eta: 1 day, 1:38:24, time: 0.761, data_time: 0.007, memory: 9025, loss_ProbiouLoss: nan, IOU_mean: nan, loss_QualityFocalLoss: nan, loss: nan, grad_norm: nan
2022-01-25 11:08:40,862 - mmdet - INFO - Exp name: fcosr_rx101_64x4d_fpn_3x_dota10_single.py
2022-01-25 11:08:40,862 - mmdet - INFO - Epoch [5][1230/1230]   lr: 1.000e-02, eta: 1 day, 1:38:10, time: 0.760, data_time: 0.007, memory: 9025, loss_ProbiouLoss: nan, IOU_mean: nan, loss_QualityFocalLoss: nan, loss: nan, grad_norm: nan
2022-01-25 11:08:40,960 - mmdet - INFO - Saving checkpoint at 5 epochs
[                                                  ] 0/2587, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/train.py", line 189, in <module>
    main()
  File "tools/train.py", line 185, in main
    meta=meta)
  File "/root/FCOSR-master/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/envs/pytorch1.6/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/envs/pytorch1.6/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/opt/conda/envs/pytorch1.6/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/opt/conda/envs/pytorch1.6/lib/python3.7/site-packages/mmcv/runner/hooks/evaluation.py", line 220, in after_train_epoch
    self._do_evaluate(runner)
  File "/root/FCOSR-master/mmdet/core/evaluation/eval_hooks.py", line 17, in _do_evaluate
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "/root/FCOSR-master/mmdet/apis/test.py", line 27, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/opt/conda/envs/pytorch1.6/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/pytorch1.6/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "/opt/conda/envs/pytorch1.6/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/envs/pytorch1.6/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/pytorch1.6/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/root/FCOSR-master/mmdet/models/detectors/base.py", line 173, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/root/FCOSR-master/mmdet/models/detectors/base.py", line 146, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/root/FCOSR-master/mmdet/models/rbox/fcosr.py", line 116, in simple_test
    bbox_list = self.rbbox_head.get_rbboxes(*bbox_inputs)
  File "/root/FCOSR-master/mmdet/models/rbox/fcosr_head.py", line 397, in get_rbboxes
    cls_score_list, rbbox_pred_list, mlvl_points, img_shape, scale_factor, cfg, rescale)
  File "/root/FCOSR-master/mmdet/models/rbox/fcosr_head.py", line 538, in get_rbboxes_single
    corners = self.rotate2corner(self.vector2bbox(points, rbbox_pred.clone()))
  File "/root/FCOSR-master/mmdet/models/rbox/fcosr_head.py", line 765, in rotate2corner
    return fcosr_tools.rbox2corner(rboxs)

Loss为nan值的哪个Epoch训练结束，验证时报错，这是怎么回事？怎样解决？

**Comment by lzh420202** [comment]
如果是训练阶段的验证，那这个确实有点问题，我们也没有解决，所以我们在训练时候会加入--no-valide选项。至于你提到的nan，可能需要调整学习率（一般是调小），这个是我们发现的情况。
